[package]
name = "adventofcode2019rust"
version = "0.1.0"
authors = ["Patrick Collins <pat@burned.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rayon = "1.2.1"
