version: 2.1
orbs:
  rust: glotrade/rust@0.1.3
jobs:
  check:
    executor: rust/default
    steps:
      - rust/checkout_with_submodules
      - rust/update_toolchain
      - rust/check
      - rust/clippy
      - rust/format
  test:
    executor: rust/default
    steps:
      - rust/checkout_with_submodules
      - rust/update_toolchain
      - rust/test
      - run: 'cargo test --all --ignored'
workflows:
  build:
    jobs:
      - check
      - test
