version: 2.1
orbs:
  rust: glotrade/rust@0.1.3
workflows:
  build:
    jobs:
      - check:
          steps:
            - rust/check
            - rust/clippy
            - rust/format
      - test:
          steps:
            - rust/test
