version: 2.1
orbs:
  rust: glotrade/rust@0.1.3
jobs:
  check:
    executor: rust/default
    steps:
      - rust/check
      - rust/clippy
      - rust/format
  test:
    executor: rust/default
    steps:
      - rust/test
workflows:
  build:
    jobs:
      - check
      - test
